import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Providers from "./providers";

const poppins = Poppins({
  subsets: ["latin"], // Choose the subsets you need
  weight: ["300", "400", "500", "600", "700"], // Select the font weights you need
  variable: "--font-poppins", // Define a custom variable name for the font
});



export const metadata: Metadata = {
  title: "Devs.com",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${poppins.variable} antialiased`}
      >
       <Providers>
       {children}
       </Providers>
      </body>
    </html>
  );
}
